### ISSUE TITLE
Add different "run modes"

### ISSUE THREAD

**Issue by dabo505** [zazuko/barnard59#94]
If a pipeline that takes in a lot of data e.g. from an API constantly fails at some point it can take a long time to fix it, because on has to rerun it everytime (which might then take hours until the problem occurs again). 
In the discussion in the [Tactical](https://github.com/zazuko/admin/issues/60) we agreed that the "failing pipeline mode" is still a good default as it prevents the publication of inconsistent datasets. 
- [ ] For some cases it might be helpful to have a "force mode" that does `on error resume next` and just logs the errors as they occur. 
- [ ] Also it would be great to have a "retry option" with certain specifications and setup a proactive log

**Comment by dabo505** [comment]
@ludovicm67 @giacomociti @tpluscode Feel free to change my description or add to it, so it's more clear...

**Comment by ludovicm67** [comment]
By default, it's great to make the pipeline fail once an error is happening.
I don't know if a `allowFailure` parameter can be configured at step level and globally to ignore a failure and continue the pipeline?
But if the step after expect something that was transformed from a format to another, for example, the pipeline should fail.

For data transformation, it can be also nice to have a way to ignore broken triples/quads (and displaying them in the logs and explaining the reason why there was an issue), so that other valid triples/quads can continue to be streamed to other steps, and make sure we get a result at the end, even if it's incomplete.
For this, I see it like a dedicated option to add to a step, maybe `ignoreInvalidData` or something like this.

Regarding the retry option, it could be great that steps that are doing some HTTP requests for example can have an explicit retry option. By default, no retry is done.

In general, for pipelines that are run using GitLab CI, it's great to have a dedicated job for each important step. And then adding the `retry` option in the GitLab job will be a nice workaround for this for now.

What do you think?

**Comment by tpluscode** [comment]
I shall close this as I do not see a core feature which implements the presented scenarios

**Comment by tpluscode** [comment]
We may consider a specialised `onError` hook for individual steps which could allow retries, especially useful for transforms which rely on external services, etc

The "on error resume" idea is dangerous because it targeted a specific use case but in general can lead to confusion where pipeline succeeds but data is incomplete or otherwise wrong
